name: weather_demo
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  bloc: ^8.1.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.0
  dio: ^5.3.3
  flutter_dotenv: ^5.1.0
  pretty_dio_logger: ^1.3.1
  retrofit: ^4.0.3
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1

dev_dependencies:
  bloc_test: ^9.1.4
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0
  very_good_analysis: ^5.1.0
  build_runner: ^2.4.6
  flutter_gen_runner: ^5.3.2
  retrofit_generator: ^8.0.1
  json_serializable: ^6.7.1
  freezed: ^2.4.5

flutter_gen:
  output: lib/shared/resources/

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/environments/.dev.env
    - assets/environments/.pro.env
    - assets/environments/.stag.env